cache: bundler
dist: trusty
language: ruby
rvm:
  - 2.4.3
addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
before_install:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

env:
  matrix:
    - SOLIDUS_BRANCH=v2.5 DB=postgres
    - SOLIDUS_BRANCH=v2.6 DB=postgres
    - SOLIDUS_BRANCH=v2.7 DB=postgres
    - SOLIDUS_BRANCH=v2.8 DB=postgres
    - SOLIDUS_BRANCH=v2.9 DB=postgres
    - SOLIDUS_BRANCH=master DB=postgres
    - SOLIDUS_BRANCH=v2.5 DB=mysql
    - SOLIDUS_BRANCH=v2.6 DB=mysql
    - SOLIDUS_BRANCH=v2.7 DB=mysql
    - SOLIDUS_BRANCH=v2.8 DB=mysql
    - SOLIDUS_BRANCH=v2.9 DB=mysql
    - SOLIDUS_BRANCH=master DB=mysql
