language: ruby
rvm:
  - 2.3.3
sudo: false
cache: bundler
only: master
env:
  matrix:
    - SOLIDUS_BRANCH=v2.3 DB=mysql
    - SOLIDUS_BRANCH=v2.3 DB=postgresql
    - SOLIDUS_BRANCH=v2.4 DB=mysql
    - SOLIDUS_BRANCH=v2.4 DB=postgresql
    - SOLIDUS_BRANCH=v2.5 DB=mysql
    - SOLIDUS_BRANCH=v2.5 DB=postgresql
    - SOLIDUS_BRANCH=v2.6 DB=mysql
    - SOLIDUS_BRANCH=v2.6 DB=postgresql
    - SOLIDUS_BRANCH=master DB=mysql
    - SOLIDUS_BRANCH=master DB=postgresql
